import "./globals.css";
import type { Metadata } from "next";
import { montserrat, roboto } from "./fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Holidaze",
  description: "Generated by create next app"
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${roboto.variable} min-h-screen antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
